name: Build latest docker image for JMusicBot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * WED"
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get latest 2 releases
        id: latest_releases
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             const releases = await github.rest.repos.listReleases({
              owner: 'jagrosh',
              repo: 'MusicBot',
              per_page: 2
             });
      
             const latestReleases = releases.data.map(release => ({
              tag_name: release.tag_name,
              version: release.tag_name
             }));
      
             return latestReleases;
      
      - 
        name: Checkout repository
        uses: actions/checkout@v4
        
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Build and Push Latest Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
           JMUSICBOT_VERSION=${{ steps.latest_releases.outputs.releases[0].version }}
          tags: |
           pixelt/jmusicbot:latest
           pixelt/jmusicbot:${{ steps.latest_releases.outputs.releases[0].version }}
      
      - 
        name: Build and Push Previous Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            JMUSICBOT_VERSION=${{ steps.latest_releases.outputs.releases[1].tag_name }}
          tags: |
            ${{ github.repository }}:${{ steps.latest_releases.outputs.releases[1].tag_name }}
