name: Build latest docker image for JMusicBot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * WED"
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4

      - 
        name: Get latest releases
        id: get_releases
        run: |
          TAGS=$(curl -sSL "https://api.github.com/repos/jagrosh/musicbot/releases" | jq -r '.[].tag_name' | head -n 2)
          echo "::set-output name=tags::${TAGS}"


      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker images
        env:
          DOCKER_REPO: pixelt/jmusicbot
        run: |
          for tag in ${{ steps.get_releases.outputs.tags }}; do
            docker build -t $DOCKER_REPO:$tag --build-arg JMUSICBOT_VERSION=$tag .
            docker push $DOCKER_REPO:$tag
          done
