name: Build docker image for JMusicBot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 2 4 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jagrosh
          repo: MusicBot
          excludes: prerelease, draft

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
           pixelt/jmusicbot:latest
           pixelt/jmusicbot:0.4.3-yt.oauth2
#           pixelt/jmusicbot:${{ steps.keydb.outputs.release }}
          build-args: |
            JMUSICBOT_VERSION=0.4.3-yt.oauth2
#           JMUSICBOT_VERSION=${{ steps.keydb.outputs.release }}
