name: Build latest docker image for JMusicBot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * WED"
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get latest releases
        id: latest_releases
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jagrosh
          repo: MusicBot
          exclude: prerelease, draft
          limit: 2
          
      - 
        name: Checkout repository
        uses: actions/checkout@v4
        
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Build and Push Latest Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
           JMUSICBOT_VERSION=${{ steps.latest_releases.outputs.release1 }}
          tags: |
           pixelt/jmusicbot:latest
           pixelt/jmusicbot:${{ steps.latest_releases.outputs.release1 }}
      
      - 
        name: Build and Push Previous Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            JMUSICBOT_VERSION=${{ steps.latest_releases.outputs.release2 }}
          tags: |
            ${{ github.repository }}:${{ steps.latest_releases.outputs.release2 }}
