name: Build Stable Version of JMusicBot

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version 0.3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push Last Stable
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
           pixelt/jmusicbot:0.3.9
          build-args: |
           JMUSICBOT_VERSION=0.3.9
