name: Build MusicBot with Custom Dependency

#on:
#  push:
#    branches:
#      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repo
        uses: actions/checkout@v4
      
      - name: Clone MusicBot Repository
        run: |
          git clone https://github.com/elijahtaylorr/MusicBot.git
      
      - name: Overwrite pom.xml
        run: |
          cp ./pom.xml MusicBot/pom.xml
          cd MusicBot

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Project
        run: |
          cd MusicBot
          mvn clean install

      - name: Upload JAR 
        uses: actions/upload-artifact@v4
        with:
          name: musicbot-jar
          path: MusicBot/target/*.jar

